inherit_gem:
  rubocop-shopify: rubocop.yml

require: rubocop-rspec

AllCops:
  Include:
    - 'bin/**/*.rb'
    - 'lib/**/*.rb'
  NewCops: enable

Layout/HashAlignment:
  EnforcedColonStyle: table

Style/ClassMethodsDefinitions:
  Enabled: false

# Not sure if this improves readability or not...
Style/BitwisePredicate:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec
