inherit_gem:
  rubocop-shopify: rubocop.yml

require: rubocop-rspec

AllCops:
  Include:
    - 'bin/**/*.rb'
    - 'lib/**/*.rb'
  NewCops: enable

Layout/HashAlignment:
  EnforcedColonStyle: table

Style/ClassMethodsDefinitions:
  Enabled: false