# frozen_string_literal: true

require 'avr/version'
require 'avr/memory'
require 'avr/memory/sram'
require 'avr/memory/eeprom'
require 'avr/memory/flash'
require 'avr/register'
require 'avr/register/memory_byte_register'
require 'avr/register/memory_byte_register_with_named_bits'
require 'avr/register/register_pair'
require 'avr/register/register_file'
require 'avr/register/sreg'
require 'avr/register/sp'
require 'avr/cpu'
require 'avr/opcode_decoder'
require 'avr/opcode'
require 'avr/opcode/opcodes'
require 'avr/instruction'
require 'avr/clock'
require 'avr/oscillator'
require 'avr/device'
require 'avr/port'

require 'avr/device/atmel_atmega328p'
