name: sorbet

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  sorbet:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7.2']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run sorbet type check
        run: bundle exec srb tc
